#
# VisionZero Local Database
#

version: '3.7'
services:
    #
    # Local PostgreSQL database
    #   Note: Attempted using the leanest version (alpine), feel free
    #   to use any other image, as long as the port configuration
    #   and access configuration (user, db, password) are all the same.
    #
    visionzero-pgsql:
        image: postgis/postgis:12-master
        volumes:
            - visionzero-db-vol:/var/lib/postgresql/data
        expose:
            - 5432
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=atd_vz_data
            - POSTGRES_PASSWORD=atd_vz_data
            - POSTGRES_DB=atd_vz_data

    hasura:
        image: hasura/graphql-engine:v1.2.1
        restart: always
        depends_on:
            - visionzero-pgsql
        expose:
            - 8080
        ports:
            - 8080:8080
        environment:
            - HASURA_GRAPHQL_ENABLE_CONSOLE=true
            - HASURA_GRAPHQL_ENABLE_TELEMETRY=false
            - HASURA_GRAPHQL_DATABASE_URL=postgres://atd_vz_data:atd_vz_data@visionzero-pgsql:5432/atd_vz_data
            - HASURA_GRAPHQL_ADMIN_SECRET=atd_vz_data
volumes:
    visionzero-db-vol:
        driver: local
