services:
  graphql-engine:
    image: hasura/graphql-engine:v2.43.0
    volumes:
      - ./viewer/graphql-engine-metadata:/metadata
    container_name: visionzero-graphql-engine
    ports:
      - 8084:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://visionzero:visionzero@postgis:5432/atd_vz_data
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
  postgis:
    container_name: visionzero-postgis
    build: database
    env_file:
      - .env_gh_action
    volumes:
      - visionzero_postgis_pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  visionzero_postgis_pgdata:
    name: visionzero_postgis_pgdata
