version: '3.7'
services:
  postgis:
    container_name: visionzero_postgis
    build: atd-vzd
    env_file:
      - .env
    volumes:
      - visionzero_postgis_pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  graphql-engine:
    image: hasura/graphql-engine:v2.16.1 # can jump cleanly to this with shorter event names
    # image: hasura/graphql-engine:v1.3.3 # use this to rename the events
    volumes:
      - ./atd-vzd/graphql-engine-metadata:/metadata
    container_name: visionzero_hasura
    ports:
      - 8080:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://visionzero:visionzero@postgis:5432/atd_vz_data
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
  db-tools:
    container_name: visionzero_download_db_data
    build: atd-toolbox/download-db-data
    #command: /bin/bash -c "sleep 10 && python3 download_db_data.py"
    command: tail -f /dev/null
    env_file:
      - .env
    volumes:
      - ./atd-vzd/snapshots:/snapshots
  vze:
    container_name: visionzero_vze
    command: tail -f /dev/null
    build: atd-vze

volumes:
  visionzero_postgis_pgdata:
    name: visionzero_postgis_pgdata