#
# CircleCI Builder for Vision Zero
#

version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: "Building Packages"
          command: |
            source .circleci/docker-helper.sh
            build_containers
      - run:
          name: "Triggering netlify build"
          command: node ./.circleci/scripts/buildNetlifySite.js

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - production
