name: "Remove Unused SQS PRs"

#on:
#  pull_request:
#    types: [closed]

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: "Install AWS Cli"
        run: "pip install awscli"
      - name: "Run Cleanup Script"
        run: "echo 'Hello world!'"
