name: "Remove Unused SQS PRs"

#on:
#  pull_request:
#    types: [closed]

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: "Install AWS Cli"
        run: "pip install awscli"
      - name: "Run Cleanup Script"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "PR: $PR_NUMBER"
          echo "GR: $GITHUB_REF"
          cat $GITHUB_EVENT_PATH
