#
# This GitHub action removes PR resources created by CircleCI
# and it is only triggered whenever a PR is closed or merged.
#
name: "Remove Unused SQS PRs"

on:
  pull_request:
    types: [closed]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install AWS Cli"
        run: |
          sudo apt-get install python3-setuptools
          pip3 install awscli boto3
      - name: "Run Cleanup Script"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export BRANCH_NAME=${GITHUB_REF##*/}
          export PR_NUMBER=$(echo $GITHUB_REF | cut -d "/" -f 3)
          echo "SHA: ${GITHUB_SHA}"
          echo "PR: ${PR_NUMBER}"
          echo "ACTION: ${BRANCH_NAME}"
          echo "GR: ${GITHUB_REF}"
          echo "PWD: $(pwd)"
          ./.github/workflows/aws-lambda-helper-clean.py
