name: "Remove Unused SQS PRs"

#on:
#  pull_request:
#    types: [closed]

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install AWS Cli"
        run: |
          sudo apt-get install python3-setuptools
          pip3 install awscli boto3
      - name: "Run Cleanup Script"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export PR_NUMBER=$(curl -s -H "Accept: application/vnd.github.groot-preview+json" "https://api.github.com/repos/cityofaustin/atd-vz-data/commits/${GITHUB_SHA}/pulls" | jq -r '.[].number')
          echo "SHA: ${GITHUB_SHA}"
          echo "PR: ${PR_NUMBER}"
          echo "GR: ${GITHUB_REF}"
          echo "PWD: $(pwd)"
          ./.circleci/aws-lambda-helper-clean.py
