name: "Build Docker images and push to DockerHub"

on:
  pull_request:
    paths:
      - ".github/workflows/build_docker_images.yml"
      - "atd-etl/afd_ems_import/**"
      - "atd-etl/cris_import/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Paths filter"
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            afd_ems:
              - 'atd-etl/afd_ems_import/**'
            cris:
              - 'atd-etl/cris_import/**'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push AFD / EMS image
        if: steps.changes.outputs.afd_ems == 'true'
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: atd-etl/afd_ems_import
          push: true
          tags: atddocker/vz-afd-ems-import:${{ github.ref == 'refs/heads/production' && 'production' || 'latest' }}

      - name: Build and push CRIS import image
        if: steps.changes.outputs.cris == 'true'
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: atd-etl/cris_import
          push: true
          tags: atddocker/vz-cris-import:${{ github.ref == 'refs/heads/production' && 'production' || 'latest' }}