name: "Build EMS / AFD Docker Image and push to Docker Hub"

on:
  #push:
    #branches:
      #- main # main here, because these will not correlate to releases of the VZ Suite
    #paths:
      #- ".github/workflows/build_ems_afd_docker_image.yml"
      #- "atd-etl/afd_ems_import/**"
  pull_request:
    paths:
      - ".github/workflows/build_ems_afd_docker_image.yml"
      - "atd-etl/afd_ems_import/**"
  #workflow_dispatch:
    #inputs:
      #description:
        #default: ""
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: atd-etl/afd_ems_import
          push: true
          tags: atddocker/vz-afd-ems-import:${{ github.ref == 'refs/heads/production' && 'latest' || 'dev' }}